version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=digital_journal
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital_journal
    volumes:
      - ./backend/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/migrations/insert.sql:/docker-entrypoint-initdb.d/insert.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pg.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LOG_LEVEL=ERROR  
      - PGADMIN_DISABLE_POSTFIX=true 
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    restart: always